# Site settings
title:       aspidochelone
email:       
author:      zeruhur
description: "Yet another NSR blog"
baseurl:     "aspidochelone"
url:         "https://zeruhur.space"
date_format: "%d/%m/%Y"
header_pages:
 - about.md
# - contact.html

google_analytics:

# Optional features
animated:             true
show_related_posts:   true
show_post_footers:    false
show_social_icons:    true

# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
disqus_shortname: https-zeruhur-space-aspidochelone

# Social icons
github_username: zeruhur
twitter_username: zeruhur
linkedin_username: 
dev_username: 

# Post sharing icons
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: true
share_reddit: true
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'read minutes'
    related_posts:  'Related posts'
    post_footer:    'Lorem ipsum'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    :title
paginate:     5
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - vendor
