# Site settings
title:          Zotiquest
description:    Yet another NSR blog
#baseurl:        "/tale"
url:            "https://zotiquest.zeruhur.space"
remote_theme:   chesterhow/tale

# Author
author:
  name:         Zeruhur
  url:          https://zeruhur.space
  email:        zeruhur.games@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed  

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Permalinks
permalink: /:categories/:year/:month/:day/:title/
paginate: 10 # how many posts on a page

disqus: zotiquest